---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: contactbackendappdeployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: contactbackend
 template:
  metadata:
   name: contactbackend
   labels:
     app: contactbackend
  spec:
    containers:
    - name: contactbackendcontainer
      image: kunal325/apps55-back
      ports:
      - containerPort: 8080
---
